import Prism from 'prismjs'; import 'prismjs/components/prism-python'; import 'prismjs/components/prism-javascript'; import './styles.css';
const api='http://127.0.0.1:8000'; let sessionId=location.pathname.split('/').pop(); let socket, timer;
const app=document.querySelector('#app');
async function pythonRuntime(){if(globalThis.loadPyodide)return globalThis.loadPyodide({indexURL:'https://cdn.jsdelivr.net/pyodide/v0.27.0/full/'});await new Promise((ok,bad)=>{const tag=document.createElement('script');tag.src='https://cdn.jsdelivr.net/pyodide/v0.27.0/full/pyodide.js';tag.onload=ok;tag.onerror=bad;document.head.append(tag)});return globalThis.loadPyodide({indexURL:'https://cdn.jsdelivr.net/pyodide/v0.27.0/full/'})}
async function create(){const r=await fetch(`${api}/api/sessions`,{method:'POST'}); const s=await r.json(); location.href=`/session/${s.id}`}
function render(s){app.innerHTML=`<main><header><div><p class="eyebrow">PairPad</p><h1>Code together. Think clearly.</h1><p class="muted">A shared interview room with browser-only execution.</p></div><button id="new">New room</button></header><section class="room"><aside><span class="live">● Live collaboration</span><h2>Interview room</h2><p class="muted">Share this URL with your candidate.</p><button class="copy" id="copy">Copy room link</button><hr><label>Language<select id="language"><option value="python">Python</option><option value="javascript">JavaScript</option></select></label><button class="run" id="run">Run in browser</button><pre id="output">Ready to run safely in this browser.</pre></aside><section class="editor"><div class="editor-bar"><strong>solution.${s.language==='python'?'py':'js'}</strong><span id="status">Connected</span></div><div class="code-wrap"><pre id="highlight"><code></code></pre><textarea id="code" spellcheck="false"></textarea></div></section></section></main>`; const code=document.querySelector('#code'), language=document.querySelector('#language'), high=document.querySelector('#highlight code'); code.value=s.code; language.value=s.language;
 const paint=()=>{high.className=`language-${language.value}`;high.innerHTML=Prism.highlight(code.value,Prism.languages[language.value],language.value)}; paint();
 document.querySelector('#new').onclick=create; document.querySelector('#copy').onclick=()=>navigator.clipboard.writeText(location.href);
 code.oninput=()=>{paint();clearTimeout(timer);timer=setTimeout(()=>socket?.send(JSON.stringify({type:'update',code:code.value,language:language.value})),250)}; language.onchange=()=>{paint();socket?.send(JSON.stringify({type:'update',code:code.value,language:language.value}))};
 document.querySelector('#run').onclick=async()=>{const out=document.querySelector('#output');out.textContent='Running…';try{if(language.value==='javascript'){out.textContent=String(Function(`"use strict";${code.value}`)() ?? 'Finished.')}else{const py=await pythonRuntime();out.textContent=String(await py.runPythonAsync(code.value) ?? 'Finished.')}}catch(e){out.textContent=`Error: ${e.message}`}};
 socket=new WebSocket(`ws://127.0.0.1:8000/ws/sessions/${s.id}`);socket.onmessage=e=>{const d=JSON.parse(e.data);if(d.type==='document'&&d.code!==code.value){code.value=d.code;language.value=d.language;paint()}};socket.onclose=()=>document.querySelector('#status').textContent='Reconnecting…';}
if(!sessionId || sessionId===''){create()} else fetch(`${api}/api/sessions/${sessionId}`).then(r=>r.ok?r.json():create()).then(render);
